version: "2"
services:
  nginx:
    image: registry.shopiz.cn/library/nginx:1.13-alpine-1.0.0
    networks:
      - web
    volumes_from:
      - data
    links:
      - php-fpm:php-fpm
  php-fpm:
    image: registry.shopiz.cn/library/php:5.6-centos7-1.0.0
    networks:
      - web
    volumes_from:
      - data
  data:
    image: busybox
    networks:
      - web
    volumes:
      - $PWD/rootfs/data/etc/nginx:/data/etc/nginx
      - $PWD/rootfs/data/logs:/data/logs:rw
      - /data/wwwroot:/data/wwwroot:rw

  memcached:
    image: memcached
    ports:
      - 11211:11211

  redis:
    image: redis:3.2
    ports:
      - 6379:6379

  mysql:
    image: mysql:5.6
    ports:
      - 3306:3306
  

networks:
  web: